### ISSUE TITLE
essence20actor not working with Wild card tokens

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#170]
foundry.js:711 Error: Essence20Actor [AABkgdFfTcNOPxli] Model Validation Errors
[Essence20Actor.prototypeToken]: Model Validation Errors
[PrototypeToken.texture]: Model Validation Errors
[PrototypeToken.texture.src]: does not have a valid file extension
[No packages detected]
    at SchemaField._validateType (commons.js:3605:15)
    at SchemaField.validate (commons.js:3332:37)
    at Essence20Actor.validate (commons.js:4969:35)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12407:13)
    at ClientDatabaseBackend._updateDocuments (foundry.js:12323:33)
    at ClientDatabaseBackend.update (commons.js:6255:24)
    at async Essence20Actor.updateDocuments (commons.js:5610:23)
    at async Essence20Actor.update (commons.js:5707:23)

This is the error in the console. Basically its not allowing multisided tokens.

**Comment by phildominguez** [comment]
This happens in dnd5e for v10 as well. Closing!
